apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-private-ca-root-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-private-ca-root-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: true
  commonName: {{ .Release.Name }}-private-ca-root-cert

  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Release.Name }}-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
